{% set version = "3.3.0.23" %}

package:
  name: billiard
  version: {{ version }}

source:
  fn: billiard-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/b/billiard/billiard-{{ version }}.tar.gz
  sha256: 692a2a5a55ee39a42bcb7557930e2541da85df9ea81c6e24827f63b80cd39d0b

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - billiard
    - billiard.dummy
    - billiard.tests
    - funtests

about:
  home: http://github.com/celery/billiard
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python multiprocessing fork with improvements and bugfixes

extra:
  recipe-maintainers:
    - jakirkham
    - kwilcox
