{% set name = "billiard" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12b641b0c539073fc8d3f5b8b7be998956665c4233c7c1fcd66a7e677c4fb36f

build:
  number: 0
  skip: true # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - python
    - wheel
    - pip
  run:
    - python

test:
  source_files:
    - t
  imports:
    - billiard
    - billiard.compat
    - billiard.connection
    - billiard.dummmy
    - billiard.pool
    - billiard.process
    - billiard.queues
  requires:
    - pip
    - pytest >=6.2
    - psutil >=5.9.0
  commands:
    - pip check
    - pytest -vv t/unit
    # Integration tests are out-dated (last changes adaa178 2 years ago) and broken
    # - pytest -vv t/integration

about:
  home: https://github.com/celery/billiard
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python multiprocessing fork with improvements and bugfixes
  description: |
    billiard is a fork of the Python 2.7 multiprocessing package.
    This standalone variant draws its fixes/improvements from python-trunk
    and provides additional bug fixes and improvements.
  dev_url: https://github.com/celery/billiard

extra:
  recipe-maintainers:
    - kwilcox
    - igortg
