{% set version = "3.5.0.1" %}

package:
  name: billiard
  version: {{ version }}

source:
  fn: billiard-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/b/billiard/billiard-{{ version }}.tar.gz
  sha256: 989e5c208350ada5f37f0f187758a801457fe53e9a1d06c139796afcfafabd5b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - billiard
    - billiard.dummy

about:
  home: http://github.com/celery/billiard
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python multiprocessing fork with improvements and bugfixes

extra:
  recipe-maintainers:
    - jakirkham
    - kwilcox
