# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangpython2.7
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython2.7
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lErmjtuDDM3mOjk+tHnZj4zr/MP+UMBhuJIOLWx0OX7mlx7XiHSO4ggN7cfqe3OMGSXQJIhFXUHz1BSL2E5QzeLQgUrOxIbEDLQ0KZDPiV4h+igpqj45f9ISEGtl0ymOP1lC/XtIXvRHAy6YopJKvKlrneL3WwugW34l9Tp8Fcxjqm2SIR8hCIHNtDPpZQVA6KY0f//EaNpXUGxD2PmtP8oUTHUnJySjEWiTeExxhZh3h6Y60iDBN8sk3DKTegypjjipG0r6BlV0pGAp9ohAE+8cZtMyDE3FOORSIGbtdk+rJzkxSxGUc4GveH33NLFxi87SEwTJkFfMe2lV5GvfXjND9RwngFNoiAntNdAjX/iCpxnLoeLEs5VW55/69i7WU3TP5nvlFgWQUOUWbdcC8VZqT4svH4x+tkVGTdDV+IIaNp+nitdsDEemlAZyOPAzg961OTlBJIrkMo4jiUuH/2XYob4nwJU6N4UK53/pTYzi8dQQEBpjA3M5ctVg6MG5aiKKxCFr4VKNwzPKbgfDyltnovR0YUNHU64CJa2ZEx36t7PuaPIpMGQRHmLEhjB3oUuNTxTMSBOBrJ5xhvzgXRCFvj763jvqBf9dTLJDXi6uMeHXEGoDejnjaHAPI46Csc+B6+0YASGGgviaCvcfYfourFULHLL/4FWwIDv26LY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
