travis:
  secure:
    BINSTAR_TOKEN: D4Iw5NFYeeDWNEkIQkMVAbil+1tF71UPqKA1H6SewdbxR1iInsGXgy6NjyuWtYre6cXEQIoBt7nnZJt9XNoxtUaR5/qyPG1HD10KrhI3TVfeKDa2wtJxwUB9UIcL0UFM41E8tDj1VYYDI1O6IYMSLUN5Z5vaQFT9f3NiQbjGfwKOjMPbMXuWhbGgxD6I0gob3R2M59/JJOMpTBg2jifpbHLBApeaH1xACFsVVkzz2fXcCdiMyaOhUi+pmxp5vqs99yyrlJIvq0ansy0tH1cUvs0qArOYsMZk8bgfMeM8vDU5CKCpcXZ8bcp5/B6EZUQZR5W7BIB23yNBcKWPHZ9Aqiu1iMx8LtsLPpzY+ApKbRQLUS00tenNaDVh2ktEg4ixGDIcjb/gyF2ZdIVlS1NVrRwdykX+atQEz3u/PfFdMY0qKTVaAcqZ8j5aIofEc7lm4XY/40gDMbmEm/Rd59iMRMW6yv2I57QMaJua38eVPTYpX8LiHRQJFoyneHFD7uo+nQJjZ5j2GUoXIQ29KvdPmUpHnK9us84DbZ+m58L9Na5nrX7bJKso1lPQT8kJ1Kw9TihqOlTat5CU5Hu4KpBD/Ab+Af6M4BFiAAs0r4Lqtg74Darf2LsSBoMKfYwsTTFNVNTgV7BKLuAOohytMYKWObuAOQZq/wOL20iamMRAS4g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
